spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tony_api?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: tony_api
    password: tony_api
    driver-class-name: com.mysql.cj.jdbc.Driver
web:
  cors:
    enabled: true
jwt:
  secret: '123'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: "mybatis"
