spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tony_boot?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
web:
  cors:
    enabled: true
    allowed-origin-patterns:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
