spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  mapper-locations: classpath*:mappers/*.mapper.xml
  configuration:
    return-instance-for-empty-row: true
    default-enum-type-handler: com.tony.mybatis.typehandler.EnumTypeHandler
  global-config:
    banner: off

