INSERT INTO sys_employee (employee_id, account, real_name, employee_mobile, pwd, salt, account_state, creator_id, creator_name) VALUES ('ADMIN', 'admin', '超级管理员', '13984842424', '68846F643A26BD47B1ECE1BFA7BDAECF', 'TONY_SALT',1,'ADMIN','超级管理员');
INSERT INTO sys_role (role_id, role_name, role_code, build_in, creator_id, creator_name) VALUES ('ADMIN', '超级管理员', 'ADMIN', 1,  'ADMIN', '超级管理员');
INSERT INTO sys_employee_role(employee_id, role_id) VALUES ('ADMIN','ADMIN');

INSERT INTO sys_dict_type (dict_type_id, app_id, dict_type_code, dict_type_code_seq, dict_type_name, build_in, creator_id, creator_name) VALUES ('STATE',  '', 'STATE', 'STATE', '状态', 1,    'ADMIN', '超级管理员');
INSERT INTO sys_dict_type (dict_type_id, app_id, dict_type_code, dict_type_code_seq, dict_type_name, build_in, creator_id, creator_name) VALUES ('YES_OR_NO',  '', 'YES_OR_NO', 'YES_OR_NO', '是否', 1,   'ADMIN', '超级管理员');

INSERT INTO sys_dict (dict_id, dict_type_id, dict_name, dict_code, dict_value, dict_meta, build_in, creator_id, creator_name) VALUES ('STATE.DISABLED', 'STATE', '禁用', 'DISABLED', 'false', '{"color": "error", "valueType": "Boolean"}', 1,   'ADMIN', '超级管理员');
INSERT INTO sys_dict (dict_id, dict_type_id, dict_name, dict_code, dict_value, dict_meta, build_in, creator_id, creator_name) VALUES ('STATE.ENABLED', 'STATE', '启用', 'ENABLED', 'true', '{"color": "success", "valueType": "Boolean"}', 1,   'ADMIN', '超级管理员');
INSERT INTO sys_dict (dict_id, dict_type_id, dict_name, dict_code, dict_value, dict_meta, build_in, creator_id, creator_name) VALUES ('YES_OR_NO.NO', 'YES_OR_NO', '否', 'FALSE', 'false', '{"color": "error", "valueType": "Boolean"}', 1,  'ADMIN', '超级管理员');
INSERT INTO sys_dict (dict_id, dict_type_id, dict_name, dict_code, dict_value, dict_meta, build_in, creator_id, creator_name) VALUES ('YES_OR_NO.YES', 'YES_OR_NO', '是', 'TRUE', 'true', '{"color": "success", "valueType": "Boolean"}', 1,  'ADMIN', '超级管理员');

INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('deptAdd', '', 'system', '新增部门',  'system-deptAdd', 'deptAdd', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('deptDelete', '', 'system', '删除部门',  'system-deptDelete', 'deptDelete', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('deptList', '', 'system', '部门列表',  'system-deptList', '/sys/dept/list', 1,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('deptUpdate', '', 'system', '更新部门',  'system-deptUpdate', 'deptUpdate', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictAdd', '', 'system', '新增字典',  'system-dictAdd', 'dictAdd', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictDelete', '', 'system', '删除字典',  'system-dictDelete', 'dictDelete', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictList', '', 'system', '字典列表',  'system-dictList', '/sys/dict/list', 1,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictTypeAdd', '', 'system', '新增字典类型',  'system-dictTypeAdd', 'dictTypeAdd', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictTypeDelete', '', 'system', '删除字典类型',  'system-dictTypeDelete', 'dictTypeDelete', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictTypeUpdate', '', 'system', '更新字典类型',  'system-dictTypeUpdate', 'dictTypeUpdate', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('dictUpdate', '', 'system', '更新字典',  'system-dictUpdate', 'dictUpdate', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeAdd', '', 'system', '新增用户',  'system-employeeAdd', 'employeeAdd', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeAssignRoles', '', 'system', '分配用户角色',  'system-employeeAssignRoles', 'employeeAssignRoles', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeDelete', '', 'system', '删除用户',  'system-employeeDelete', 'employeeDelete', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeList', '', 'system', '用户列表',  'system-employeeList', '/sys/employee/list', 1,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeResetPwd', '', 'system', '重置密码',  'system-employeeResetPwd', 'employeeResetPwd', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeToggle', '', 'system', '更新用户状态',  'system-employeeToggle', 'employeeToggle', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('employeeUpdate', '', 'system', '更新用户',  'system-employeeUpdate', 'employeeUpdate', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('roleAdd', '', 'system', '新增角色', 'system-roleAdd', 'roleAdd', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('roleAssignModules', '', 'system', '功能权限',  'system-roleAssignModules', 'roleAssignModules', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('roleDelete', '', 'system', '删除角色',  'system-roleDelete', 'roleDelete', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('roleList', '', 'system', '角色列表',  'system-roleList', '/sys/role/list', 1,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('roleUpdate', '', 'system', '更新角色',  'system-roleUpdate', 'roleUpdate', 2,  '{}',  'ADMIN', '超级管理员');
INSERT INTO sys_module (module_id, app_id, parent_module_id, module_name, module_code_seq, module_value, module_type, module_meta, creator_id, creator_name) VALUES ('system', '', '', '系统管理',  'system', '/sys', 0,  '{}',  'ADMIN', '超级管理员');

