knife4j:
    enable: true
    setting:
        enable-host: true
        enable-reload-cache-parameter: true
        enable-footer: false
        enable-home-custom: true
        enable-swagger-models: false
        home-custom-location: classpath:markdown/HOME.md
    extension:
        basePackages:
            - "com.tony.api"
        title: "tony-micro-service-demo"
