spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tony-demo?serverTimezone=GMT%2B8&&characterEncoding=utf8&autoReconnect=true
    username: tony_api
    password: tony_api
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    password: "123456"
    database: 8
    timeout: 3000
