spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.51.15:3306/tony-demo?serverTimezone=GMT%2B8&&characterEncoding=utf8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: localhost
        password: "test_redi"
        database: 8
        timeout: 3000
swagger:
    base-packages:
        - "com.tony.api"
    title: "tony-micro-service-demo"
