server:
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  servlet:
    encoding:
      enabled: false
    jsp:
      registered: false
  ssl:
    enabled: false
  compression:
    enabled: true
    mime-types:
      - application/json
      - text/xml
      - text/plain
spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
    formcontent:
      filter:
        enabled: false
  freemarker:
    enabled: false
  thymeleaf:
    enabled: false
  main:
    web-application-type: servlet
  web:
    locale-resolver: fixed
