services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
        USER_NAME: $USER_NAME
        GROUP_NAME: $GROUP_NAME
    image: $GROUP_NAME/nginx
    user: $UID:$GID
    group_add:
      - $GID
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./conf.d/:/etc/nginx/conf.d/:Z
        - ./html/:/home/$USER_NAME/nginx/html/
        - ./logs/:/home/$USER_NAME/nginx/logs/
        - ./ssl/:/etc/nginx/ssl/:Z
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
