feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types:
        - text/xml
        - text/plain
        - application/xml
        - application/json
  okhttp:
    enabled: true
  httpclient:
    enabled: false

spring:
  cloud:
    openfeign:
      httpclient:
        enabled: false
      okhttp:
        enabled: true
      compression:
        request:
          enabled: true
          min-request-size: 2048
          mime-types:
            - text/xml
            - text/plain
            - application/xml
            - application/json
