springdoc:
  default-flat-param-object: on
  default-produces-media-type: "application/json"
  disable-i18n: on
  enable-spring-security: off
  enable-data-rest: off
  default-support-form-data: on
  nullable-request-parameter-enabled: on
  enable-hateoas: off
  show-spring-cloud-functions: off
  remove-broken-reference-definitions: off
  override-with-generic-response: off
  pre-loading-enabled: on
knife4j:
  enable: on
  setting:
    enable-host: on
    enable-dynamic-parameter: on
    enable-reload-cache-parameter: on
    enable-response-code: off
    enable-swagger-models: on
    enable-version: on
