springdoc:
  default-flat-param-object: true
  default-produces-media-type: "application/json"
  disable-i18n: true
  enable-spring-security: false
  enable-data-rest: false
  default-support-form-data: true
  nullable-request-parameter-enabled: true
  enable-hateoas: false
  show-spring-cloud-functions: false
  remove-broken-reference-definitions: false
  override-with-generic-response: false
  pre-loading-enabled: true
knife4j:
  enable: true
  setting:
    enable-host: true
    enable-dynamic-parameter: true
    enable-reload-cache-parameter: true
    enable-response-code: false
    enable-swagger-models: true
    enable-version: true
