networks:
  backend:
    external: true
    driver: bridge
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "15692:15692"
      - "15674:15674"
      - "61613:61613"
    networks:
      - backend