networks:
  backend:
    external: true
    driver: bridge
volumes:
  vlm_data_postgres:
    external: true
services:
  postgres:
    container_name: postgres
    image: postgres:17.1-alpine3.20
    volumes:
      - vlm_data_postgres:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/ # warn, You must convert all your .sh files from CRLF (Windows) to LF (Linux) end of line
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - backend

