mybatis-plus:
    mapper-locations: classpath*:mappers/*.mapper.xml
    configuration:
        default-enum-type-handler: com.tony.db.typehandler.EnumValueTypeHandler
spring:
    profiles:
        active: dev
    application:
        name: tony-api

