server:
  port: 10000
spring:
  profiles:
    default: dev
  application:
    name: tony-api
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 'null'
      logic-delete-value: 'CURRENT_TIMESTAMP'
  configuration:
    default-executor-type: reuse
