spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/tony_boot?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
web:
  cors:
    allowed-origins:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
    enabled: true
logging:
  config: classpath:logback-dev.xml
#  level:
#    root: DEBUG
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-exclude:
    - ${server.error.path:${error.path:/error}}
