spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tony_api?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: tony_api
    password: tony_api
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: "123456"
web:
  cors:
    enabled: true
jwt:
  secret: 'dsfnn32SDFF&*&#bfds;;,.ks^&3@'
logging:
  level:
    'dao': DEBUG
  group:
    'dao':
      - 'com.tony.demo.sys.dao'
