spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/tony_api?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: tony_api
    password: tony_api
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: "123456"
web:
  cors:
    enabled: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-exclude:
    - ${server.error.path:${error.path:/error}}
jwt:
  secret: 'dsfnn32SDFF&*&#bfds;;,.ks^&3@'

