mybatis-plus:
    mapper-locations: classpath*:mappers/*.mapper.xml
    configuration:
        default-enum-type-handler: com.tony.db.typehandler.EnumValueTypeHandler
    global-config:
        banner: off
spring:
    profiles:
        active: dev
    application:
        name: tony-api
    main:
        banner-mode: off
