spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.31.51:3306/tony_api?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: tony_api
    password: tony_api
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: "123456"
web:
  cors:
    allowed-origins:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
    enabled: true
jwt:
  secret: 'dsfnn32SDFF&*&#bfds;;,.ks^&3@'
