server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tony_api?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: tony_api
    password: tony_api
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: "redis"
      password: "123456"
web:
  cors:
    allowed-origins:
      - "http://localhost:*"
      - "http://localhost"
      - "http://127.0.0.1:*"
      - "http://127.0.0.1"
    enabled: true
jwt:
  secret: 'dsfnn32SDFF&*&#bfds;;,.ks^&3@'
