spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/tony_boot?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    config:
        import: classpath:swagger.yaml
web:
    cors:
        allowed-origins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
        enabled: on
debug: off
logging:
    config: classpath:logback-dev.xml
